# NODE PARAMETERS
node_freq: 20                           # NODE FREQUENCY


# PREPROCESSING PARAMETERS
preprocessing:
  desired_width: 640                    # WIDTH OF RESIZED IMAGES
  clahe: true                           # FLAG FOR CLAHE APPLICATION 
  clip_limit: 1                         # CONTRAST LEVEL


# VO PARAMETERS
vo_params:
  min_num_features: 20.0                # MINIMUM NUMBER OF FEATURES REQUIRED IN AN IMAGE 
  min_num_tracked_features: 200.0       # MINIMUM NUMBER OF TRACKED FEATURES BEFORE RESETTING
  min_num_3Dpoints: 3.0                 # MINIMUM NUMBER OF TRIANGULATED POINTS
  min_num_inliers: 5.0                  # MINIMUM NUMBER OF INLIERS AFTER RANSAC  

  distance: 0.1                         # THRESHOLD USED TO EVALUATE BASELINE IN IMAGE PAIRS [px]
  max_skipped_imgs: 2                   # MAX NUMBER OF SKIPPED IMAGES

  feature_tracking: true                # FLAG FOR FEATURE CORRESPONDENCE (TRUE: TRACKING | FALSE: MATCHING)

  # RANSAC PARAMS ESSENTIAL MATRIX
  essential_max_iters: 2000             
  essential_confidence: 0.99
  essential_threshold: 0.1

  # RANSAC PARAMS HOMOGRAPHY MATRIX
  homography_max_iters: 2000
  homography_confidence: 0.99
  homography_threshold: 0.3

  homography_distance: 50.0             # MAX DISTANCE FOR TRIANGULATED POINTS USING HOMOGRAPHY
  valid_point_fraction: 0.8             # THRESHOLD USED FOR THE CHIERALITY CHECK
  reprojection_threshold: 0.1           # THRESHOLD FOR REPROJECTION ERROR USED TO EVALUATE TRIANGULATED POINTS  


# VISUALIZATION PARAMETERS
visualization:
  fps: 100 
  show_match: true                      # FLAG USED FOR SHOWING MATCHED FEATURES


# SURF PARAMETERS
surf_params:
  min_hessian: 100
  n_octaves: 4
  n_octave_layers: 3
  extended: false
  upright: true
  lowe_ratio: true
  ratio_test: 0.7
