# NODE PARAMETERS
node_freq: 20                           # NODE FREQUENCY                        


# PREPROCESSING PARAMETERS
preprocessing:
  desired_width: 740                    # WIDTH OF RESIZED IMAGES
  clahe: true                           # FLAG FOR CLAHE APPLICATION
  clip_limit: 8                         # CONTRAST LEVEL


# VO PARAMETERS
vo_params:
  min_num_features: 20.0                # MINIMUM NUMBER OF FEATURES REQUIRED IN AN IMAGE 
  min_num_3Dpoints: 3.0                 # MINIMUM NUMBER OF TRIANGULATED POINTS
  min_num_inliers: 5.0                  # MINIMUM NUMBER OF INLIERS AFTER RANSAC 

  feature_tracking: true                # FLAG FOR FEATURE CORRESPONDENCE (TRUE: TRACKING | FALSE: MATCHING)

  # PnP RANSAC PARAMETERS
  iterations_count: 100  
  reprojection_error: 8.0  
  confidence: 0.99 
  use_extrinsic_guess: false

  reprojection_threshold: 0.1           # THRESHOLD FOR REPROJECTION ERROR USED TO EVALUATE TRIANGULATED POINTS  


# VISUALIZATION PARAMETERS
visualization:
  fps: 100 
  show_match: true                      # FLAG USED FOR SHOWING MATCHED FEATURES


# SURF PARAMETERS
surf_params:
  min_hessian: 100
  n_octaves: 4
  n_octave_layers: 3
  extended: false
  upright: true
  lowe_ratio: true
  ratio_test: 0.7