#######################################################################################################################
###############################################  DOWNWARD CAMERA PARAMETERS ###########################################
#######################################################################################################################

downward_camera:

  camera_intrinsic:
    fx: 2305.660253962050
    fy: 2303.950911497790
    ccx: 1281.944364189583
    ccy: 1028.352241411627

  distortion_coefficient:
    radial:
      k1: 0.08
      k2: 0.45
    tangential:
      p1: 0.0
      p2: 0.0

#######################################################################################################################
#######################################################################################################################
#######################################################################################################################


#######################################################################################################################
################################################ FRONTAL CAMERA PARAMETERS ############################################
#######################################################################################################################

frontal_camera:

  camera_intrinsic:
    fx: 1.335036735254999e+03
    fy: 1.332419247540885e+03
    ccx: 0.644564474737301e+03
    ccy: 0.357685235527149e+03

  distortion_coefficient:
    radial:
      k1: 0.475667186716851
      k2: 0.126480045385593
    tangential:
      p1: 0.0
      p2: 0.0
