#######################################################################################################################
################################################ FRONTAL CAMERA PARAMETERS ############################################
#######################################################################################################################

frontal_camera:

  camera_intrinsic_left:
    fx: 1.335036735254999e+03
    fy: 1.332419247540885e+03
    ccx: 0.644564474737301e+03
    ccy: 0.357685235527149e+03
    
  camera_intrinsic_right:
    fx: 1.330461901943011e+03
    fy: 1.328225165048530e+03
    ccx: 0.684598875987595e+03
    ccy: 0.382841174819059e+03

  distortion_coefficient_left:
    radial:
      k1: 0.475667186716851
      k2: 0.126480045385593
    tangential:
      p1: 0.0
      p2: 0.0

  distortion_coefficient_right:
    radial:
      k1: 0.493006394402676
      k2: 0.037112494470407
    tangential:
      p1: 0.0
      p2: 0.0

  left_camera_rotation_matrix:
    rows: 3
    cols: 3
    data: [1, 0, 0, 0, 1, 0, 0, 0, 1]

  left_camera_translation_vector:
    rows: 3
    cols: 1
    data: [0, 0, 0]

  right_camera_rotation_matrix:
    rows: 3
    cols: 3
    data: [1, 0, 0, 0, 1, 0, 0, 0, 1]

  right_camera_translation_vector:
    rows: 3
    cols: 1
    data: [-0.33, 0.0, 0.0]


# ---------------------------------------------------------------------------------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------------------------------------------------------------------------------- #